#ifndef ENUMGAME_H
#define ENUMGAME_H

enum
{

	GAMEMODE, TITLEMODE, CLICKTOSTART, FOCUSMODE, MAPMODE, TELEPORTERMODE, GAMECOMPLETE,  GAMECOMPLETE2, EDITORMODE, PRELOADER, TWEAKMENUMODE

};

#endif /* ENUMGAME_H */
